required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen"
]

[[override]]
  name = "github.com/gardener/gardener"
  branch = "gardener-extensions-fixes"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "0.1.11"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.4"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.4"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.4"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.13.4"

[[constraint]]
  name = "github.com/hashicorp/go-multierror"
  revision = "3d5d8f294aa03d8e98859feac328afbdf1ae0703"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[override]]
  name = "github.com/go-logr/logr"
  version = "0.1.0"

# Dependencies for testing purposes only

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "~1.3.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "~1.4.0"

[prune]
  unused-packages = true
  go-tests = true
  non-go = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    non-go = false

  [[prune.project]]
    name = "github.com/golang/mock"
    unused-packages = false
